name: Validate PR

on:
  pull_request:
    branches:
      - main
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pull_request_validator:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR
        env: 
          GITHUB_TOKEN: ${{ secrets.github_token }}
        uses: ./.github/actions/pr_validator
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
